import type { GameState, Piece, Side } from './hybrid-engine';

export interface ExpectedHorizonCount {
  horizon: number;
  wins: number;
  losses: number;
  unresolved: number;
}

export interface ExpectedReplyStats {
  edges: number;
  min: number;
  max: number;
  average: number;
}

export interface Puzzle {
  id: string;
  number: string;
  title: string;
  subtitle: string;
  material: '2 VS 4' | '3 VS 4' | '3 VS 5';
  human: Side;
  proofDepth: number;
  mateMoves: number;
  winnerTurns: number;
  uniqueWinnerTurns: number;
  maxWinningMoves: number;
  expectedWinningMoveKeys: string[];
  expectedPrincipalVariationKeys: string[];
  expectedHorizonCounts: ExpectedHorizonCount[];
  expectedReplyStats: ExpectedReplyStats;
  hint: string;
  motif: string;
  state: GameState;
}

const p = (id: string, side: Side, type: Piece['type'], x: number, y: number): Piece => ({ id, side, type, x, y });
const horizons = (counts: Array<[wins: number, losses: number, unresolved: number]>): ExpectedHorizonCount[] => (
  counts.map(([wins, losses, unresolved], index) => ({ horizon: index + 1, wins, losses, unresolved }))
);

export const PUZZLES: Puzzle[] = [
  {
    id: 'three-branch-queen-net',
    number: '01',
    title: '三岔后网',
    subtitle: '你执象棋。首车横切后，黑方仍有三种合法防守；无论选择哪一支，第二次胜着都保持唯一。',
    material: '3 VS 5',
    human: 'xiangqi',
    proofDepth: 7,
    mateMoves: 2,
    winnerTurns: 2,
    uniqueWinnerTurns: 2,
    maxWinningMoves: 1,
    expectedWinningMoveKeys: ['28-08'],
    expectedPrincipalVariationKeys: ['28-08', '16-06', '08-06'],
    expectedHorizonCounts: horizons([[0, 0, 26], [0, 0, 26], [1, 0, 25], [1, 2, 23], [1, 2, 23], [1, 13, 12], [1, 13, 12]]),
    expectedReplyStats: { edges: 790, min: 3, max: 43, average: 30.38 },
    hint: '先把 c2 车横到 a2，等黑后进入 a4 后再沿 a 线收网。',
    motif: '三防全覆盖 · 横切 · 唯一双步',
    state: {
      turn: 'xiangqi',
      ply: 0,
      pieces: [
        p('x-general', 'xiangqi', 'general', 3, 9),
        p('x-chariot-low', 'xiangqi', 'chariot', 2, 8),
        p('x-chariot-high', 'xiangqi', 'chariot', 1, 3),
        p('c-king', 'chess', 'king', 0, 1),
        p('c-pawn-edge', 'chess', 'pawn', 7, 2),
        p('c-queen', 'chess', 'queen', 1, 6),
        p('c-pawn-top', 'chess', 'pawn', 2, 0),
        p('c-knight', 'chess', 'knight', 3, 3),
      ],
    },
  },
  {
    id: 'two-defense-rook-thread',
    number: '02',
    title: '双防穿针',
    subtitle: '你执国际象棋。少两子仍可强胜；红方有两种防守分支，但白车的两次落点在全部分支中都唯一。',
    material: '2 VS 4',
    human: 'chess',
    proofDepth: 7,
    mateMoves: 2,
    winnerTurns: 2,
    uniqueWinnerTurns: 2,
    maxWinningMoves: 1,
    expectedWinningMoveKeys: ['22-32'],
    expectedPrincipalVariationKeys: ['22-32', '55-34', '32-34'],
    expectedHorizonCounts: horizons([[0, 0, 22], [0, 0, 22], [1, 0, 21], [1, 0, 21], [1, 0, 21], [1, 0, 21], [1, 0, 21]]),
    expectedReplyStats: { edges: 558, min: 1, max: 28, average: 25.36 },
    hint: '白车先从 c8 到 d8；红马若垫到 d6，第二车必须立即吃入。',
    motif: '双防分支 · 穿针 · 以少胜多',
    state: {
      turn: 'chess',
      ply: 0,
      pieces: [
        p('x-general', 'xiangqi', 'general', 3, 7),
        p('x-chariot-low', 'xiangqi', 'chariot', 4, 8),
        p('x-horse', 'xiangqi', 'horse', 5, 5),
        p('x-chariot-high', 'xiangqi', 'chariot', 4, 7),
        p('c-king', 'chess', 'king', 0, 3),
        p('c-rook', 'chess', 'rook', 2, 2),
      ],
    },
  },
  {
    id: 'bishop-crossfire',
    number: '03',
    title: '双象交火',
    subtitle: '你执国际象棋。没有后与车，双象仍能利用九宫边界完成交叉封锁；两次胜着来自不同的象。',
    material: '3 VS 5',
    human: 'chess',
    proofDepth: 7,
    mateMoves: 2,
    winnerTurns: 2,
    uniqueWinnerTurns: 2,
    maxWinningMoves: 1,
    expectedWinningMoveKeys: ['55-66'],
    expectedPrincipalVariationKeys: ['55-66', '57-47', '76-58'],
    expectedHorizonCounts: horizons([[0, 0, 29], [0, 0, 29], [1, 0, 28], [1, 0, 28], [1, 0, 28], [1, 0, 28], [1, 0, 28]]),
    expectedReplyStats: { edges: 445, min: 1, max: 18, average: 15.34 },
    hint: '先让 f5 的象去 g4压缩九宫，再观察 h4 象通往 f2 的斜线。',
    motif: '双象协作 · 九宫边界 · 交叉封锁',
    state: {
      turn: 'chess',
      ply: 0,
      pieces: [
        p('x-general', 'xiangqi', 'general', 5, 7),
        p('x-elephant-right', 'xiangqi', 'elephant', 8, 7),
        p('x-elephant-left', 'xiangqi', 'elephant', 2, 7),
        p('x-advisor', 'xiangqi', 'advisor', 3, 7),
        p('x-chariot', 'xiangqi', 'chariot', 8, 9),
        p('c-king', 'chess', 'king', 0, 1),
        p('c-bishop-right', 'chess', 'bishop', 7, 6),
        p('c-bishop-center', 'chess', 'bishop', 5, 5),
      ],
    },
  },
  {
    id: 'corner-file-recapture',
    number: '04',
    title: '角线回收',
    subtitle: '你执象棋。黑方后象看似围住西洋王，红车却能把最远端的回防引到同一条边线再吃回。',
    material: '3 VS 5',
    human: 'xiangqi',
    proofDepth: 7,
    mateMoves: 2,
    winnerTurns: 2,
    uniqueWinnerTurns: 2,
    maxWinningMoves: 1,
    expectedWinningMoveKeys: ['79-89'],
    expectedPrincipalVariationKeys: ['79-89', '22-88', '89-88'],
    expectedHorizonCounts: horizons([[0, 0, 29], [0, 0, 29], [1, 0, 28], [1, 23, 5], [1, 23, 5], [1, 26, 2], [1, 26, 2]]),
    expectedReplyStats: { edges: 1369, min: 1, max: 54, average: 47.21 },
    hint: 'h1 车先走 i1；黑后从 c8 赶到 i2 后，沿同一纵线完成回收。',
    motif: '远端引离 · 边线回收 · 双车',
    state: {
      turn: 'xiangqi',
      ply: 0,
      pieces: [
        p('x-general', 'xiangqi', 'general', 5, 8),
        p('x-chariot-low', 'xiangqi', 'chariot', 7, 9),
        p('x-chariot-high', 'xiangqi', 'chariot', 7, 0),
        p('c-king', 'chess', 'king', 8, 2),
        p('c-queen-left', 'chess', 'queen', 2, 2),
        p('c-queen-corner', 'chess', 'queen', 8, 0),
        p('c-bishop-edge', 'chess', 'bishop', 8, 1),
        p('c-bishop-top', 'chess', 'bishop', 6, 0),
      ],
    },
  },
  {
    id: 'seventh-rank-lure',
    number: '05',
    title: '七线诱车',
    subtitle: '你执国际象棋。白车横移一格制造唯一杀网；红车被迫侧挡后，第二步沿纵线完成终局。',
    material: '3 VS 4',
    human: 'chess',
    proofDepth: 7,
    mateMoves: 2,
    winnerTurns: 2,
    uniqueWinnerTurns: 2,
    maxWinningMoves: 1,
    expectedWinningMoveKeys: ['43-53'],
    expectedPrincipalVariationKeys: ['43-53', '45-55', '53-55'],
    expectedHorizonCounts: horizons([[0, 0, 24], [0, 0, 24], [1, 0, 23], [1, 0, 23], [1, 0, 23], [1, 0, 23], [1, 0, 23]]),
    expectedReplyStats: { edges: 671, min: 1, max: 32, average: 27.96 },
    hint: 'e7 车只横移到 f7；不要急着吃 e5 的红车。',
    motif: '诱离 · 横后直取 · 唯一节奏',
    state: {
      turn: 'chess',
      ply: 0,
      pieces: [
        p('x-general', 'xiangqi', 'general', 5, 9),
        p('x-chariot-high', 'xiangqi', 'chariot', 4, 5),
        p('x-chariot-low', 'xiangqi', 'chariot', 4, 9),
        p('x-cannon', 'xiangqi', 'cannon', 2, 9),
        p('c-king', 'chess', 'king', 8, 4),
        p('c-bishop', 'chess', 'bishop', 6, 9),
        p('c-rook', 'chess', 'rook', 4, 3),
      ],
    },
  },
  {
    id: 'advisor-deflection',
    number: '06',
    title: '仕线偏转',
    subtitle: '你执国际象棋。红仕是唯一能延缓终局的防守子；白车必须先占 d8，再在它落到 d3 时吃入。',
    material: '2 VS 4',
    human: 'chess',
    proofDepth: 7,
    mateMoves: 2,
    winnerTurns: 2,
    uniqueWinnerTurns: 2,
    maxWinningMoves: 1,
    expectedWinningMoveKeys: ['12-32'],
    expectedPrincipalVariationKeys: ['12-32', '48-37', '32-37'],
    expectedHorizonCounts: horizons([[0, 0, 18], [0, 0, 18], [1, 0, 17], [1, 0, 17], [1, 0, 17], [1, 0, 17], [1, 0, 17]]),
    expectedReplyStats: { edges: 153, min: 1, max: 9, average: 8.5 },
    hint: '从 b8 横到 d8，不要沿 b 线直接下压。',
    motif: '仕线偏转 · 单车强胜 · 两步唯一',
    state: {
      turn: 'chess',
      ply: 0,
      pieces: [
        p('x-general', 'xiangqi', 'general', 3, 9),
        p('x-soldier', 'xiangqi', 'soldier', 1, 7),
        p('x-chariot', 'xiangqi', 'chariot', 4, 9),
        p('x-advisor', 'xiangqi', 'advisor', 4, 8),
        p('c-king', 'chess', 'king', 0, 0),
        p('c-rook', 'chess', 'rook', 1, 2),
      ],
    },
  },
  {
    id: 'queen-on-eighth',
    number: '07',
    title: '后落八线',
    subtitle: '你执象棋。第一步不是将军，而是长车吃后；黑王唯一退到角落后，第二车沿整条八线完成杀局。',
    material: '3 VS 4',
    human: 'xiangqi',
    proofDepth: 7,
    mateMoves: 2,
    winnerTurns: 2,
    uniqueWinnerTurns: 2,
    maxWinningMoves: 1,
    expectedWinningMoveKeys: ['12-82'],
    expectedPrincipalVariationKeys: ['12-82', '01-00', '82-02'],
    expectedHorizonCounts: horizons([[0, 0, 16], [0, 0, 16], [1, 0, 15], [1, 4, 11], [1, 4, 11], [1, 5, 10], [1, 5, 10]]),
    expectedReplyStats: { edges: 282, min: 1, max: 39, average: 17.63 },
    hint: 'b8 车先横穿到 i8 吃后；黑王退角后再回到 a8。',
    motif: '先取后 · 长线回转 · 安静首着',
    state: {
      turn: 'xiangqi',
      ply: 0,
      pieces: [
        p('x-general', 'xiangqi', 'general', 4, 9),
        p('x-chariot', 'xiangqi', 'chariot', 1, 2),
        p('x-horse', 'xiangqi', 'horse', 1, 3),
        p('c-king', 'chess', 'king', 0, 1),
        p('c-rook', 'chess', 'rook', 1, 0),
        p('c-knight', 'chess', 'knight', 1, 1),
        p('c-queen', 'chess', 'queen', 8, 2),
      ],
    },
  },
  {
    id: 'elephant-interpose',
    number: '08',
    title: '相垫中宫',
    subtitle: '你执国际象棋。白车先占 e10，逼红相从 g5 垫到 e3；同一辆车随后纵贯七格完成终局。',
    material: '2 VS 4',
    human: 'chess',
    proofDepth: 7,
    mateMoves: 2,
    winnerTurns: 2,
    uniqueWinnerTurns: 2,
    maxWinningMoves: 1,
    expectedWinningMoveKeys: ['30-40'],
    expectedPrincipalVariationKeys: ['30-40', '65-47', '40-47'],
    expectedHorizonCounts: horizons([[0, 0, 19], [0, 0, 19], [1, 0, 18], [1, 0, 18], [1, 0, 18], [1, 0, 18], [1, 0, 18]]),
    expectedReplyStats: { edges: 87, min: 1, max: 5, average: 4.58 },
    hint: 'd10 车只需走到 e10；红相垫入后，沿 e 线直接吃到 e3。',
    motif: '相垫 · 纵贯 · 单车强胜',
    state: {
      turn: 'chess',
      ply: 0,
      pieces: [
        p('c-king', 'chess', 'king', 0, 0),
        p('c-rook', 'chess', 'rook', 3, 0),
        p('x-general', 'xiangqi', 'general', 4, 9),
        p('x-block-left', 'xiangqi', 'soldier', 3, 9),
        p('x-block-right', 'xiangqi', 'soldier', 5, 9),
        p('x-elephant', 'xiangqi', 'elephant', 6, 5),
      ],
    },
  },
  {
    id: 'nine-ply-a-file-knight-net',
    number: '09',
    title: '九层引马',
    subtitle: '你执国际象棋。11 个合法首着中，只有白车先升到 a3 能把杀程精确保持到 M5；前两次胜方决策唯一，后续每个节点至多三条胜着。',
    material: '3 VS 4',
    human: 'chess',
    proofDepth: 9,
    mateMoves: 5,
    winnerTurns: 5,
    uniqueWinnerTurns: 2,
    maxWinningMoves: 3,
    expectedWinningMoveKeys: ['09-07'],
    expectedPrincipalVariationKeys: ['09-07', '37-38', '07-47', '06-05', '10-22', '05-04', '22-34', '04-03', '34-26'],
    expectedHorizonCounts: horizons([[0, 0, 11], [0, 0, 11], [0, 0, 11], [0, 0, 11], [0, 0, 11], [0, 0, 11], [0, 0, 11], [0, 0, 11], [1, 0, 10]]),
    expectedReplyStats: { edges: 45, min: 1, max: 5, average: 4.09 },
    hint: '不要急着横吃 d1 的兵；先把 a1 白车抬到 a3，迫使红帅下移，再用车横封、马走三跳。',
    motif: '静着抬车 · 三跳马网 · H9 首证',
    state: {
      turn: 'chess',
      ply: 0,
      pieces: [
        p('c-king', 'chess', 'king', 0, 0),
        p('c-rook', 'chess', 'rook', 0, 9),
        p('c-knight', 'chess', 'knight', 1, 0),
        p('x-general', 'xiangqi', 'general', 3, 7),
        p('x-block-left', 'xiangqi', 'soldier', 3, 9),
        p('x-block-right', 'xiangqi', 'soldier', 5, 9),
        p('x-screen', 'xiangqi', 'soldier', 0, 6),
      ],
    },
  },
  {
    id: 'nine-ply-solitary-knight-route',
    number: '10',
    title: '五着孤径',
    subtitle: '你执国际象棋。白马从 h10 出发；在 16 条守方边覆盖到的 17 个胜方决策点上，每次都恰好只有一个继续获胜的走法。',
    material: '3 VS 4',
    human: 'chess',
    proofDepth: 9,
    mateMoves: 5,
    winnerTurns: 5,
    uniqueWinnerTurns: 5,
    maxWinningMoves: 1,
    expectedWinningMoveKeys: ['09-07'],
    expectedPrincipalVariationKeys: ['09-07', '37-38', '07-47', '06-05', '70-62', '05-04', '62-54', '04-03', '54-46'],
    expectedHorizonCounts: horizons([[0, 0, 12], [0, 0, 12], [0, 0, 12], [0, 0, 12], [0, 0, 12], [0, 0, 12], [0, 0, 12], [0, 0, 12], [1, 0, 11]]),
    expectedReplyStats: { edges: 50, min: 1, max: 5, average: 4.17 },
    hint: '车仍要先走 a1–a3；封住第三横线后，白马沿 h10–g8–f6–e4 收束王域。',
    motif: '全程唯一 · 远马三跳 · H9 首证',
    state: {
      turn: 'chess',
      ply: 0,
      pieces: [
        p('c-king', 'chess', 'king', 0, 0),
        p('c-rook', 'chess', 'rook', 0, 9),
        p('c-knight', 'chess', 'knight', 7, 0),
        p('x-general', 'xiangqi', 'general', 3, 7),
        p('x-block-left', 'xiangqi', 'soldier', 3, 9),
        p('x-block-right', 'xiangqi', 'soldier', 5, 9),
        p('x-screen', 'xiangqi', 'soldier', 0, 6),
      ],
    },
  },
  {
    id: 'nine-ply-capture-the-screen',
    number: '11',
    title: '先取前兵',
    subtitle: '你执国际象棋。红兵已经顶到 a3；白车必须先吃兵再横封，随后白马与 f 线兵形成精确五着竞速。',
    material: '3 VS 4',
    human: 'chess',
    proofDepth: 9,
    mateMoves: 5,
    winnerTurns: 5,
    uniqueWinnerTurns: 2,
    maxWinningMoves: 3,
    expectedWinningMoveKeys: ['09-07'],
    expectedPrincipalVariationKeys: ['09-07', '37-38', '07-47', '59-58', '10-02', '58-57', '02-14', '57-56', '14-26'],
    expectedHorizonCounts: horizons([[0, 0, 10], [0, 0, 10], [0, 0, 10], [0, 0, 10], [0, 0, 10], [0, 0, 10], [0, 0, 10], [0, 0, 10], [1, 0, 9]]),
    expectedReplyStats: { edges: 41, min: 1, max: 5, average: 4.1 },
    hint: '第一步是 a1×a3；红帅退后先横车封线，再让白马从左翼三跳。',
    motif: '先吃后封 · 兵马竞速 · H9 首证',
    state: {
      turn: 'chess',
      ply: 0,
      pieces: [
        p('c-king', 'chess', 'king', 0, 0),
        p('c-rook', 'chess', 'rook', 0, 9),
        p('c-knight', 'chess', 'knight', 1, 0),
        p('x-general', 'xiangqi', 'general', 3, 7),
        p('x-block-left', 'xiangqi', 'soldier', 3, 9),
        p('x-block-right', 'xiangqi', 'soldier', 5, 9),
        p('x-screen', 'xiangqi', 'soldier', 0, 7),
      ],
    },
  },
  {
    id: 'nine-ply-sixty-six-defense-tree',
    number: '12',
    title: '六十六防线',
    subtitle: '你执国际象棋。根节点有 16 个合法首着；唯一胜着必须覆盖 66 条深层防守边，d8 红兵的侧移与前进都不能改变 M5 结论。',
    material: '3 VS 4',
    human: 'chess',
    proofDepth: 9,
    mateMoves: 5,
    winnerTurns: 5,
    uniqueWinnerTurns: 2,
    maxWinningMoves: 3,
    expectedWinningMoveKeys: ['09-07'],
    expectedPrincipalVariationKeys: ['09-07', '37-38', '07-47', '59-58', '10-02', '32-22', '02-14', '22-21', '14-26'],
    expectedHorizonCounts: horizons([[0, 0, 16], [0, 0, 16], [0, 0, 16], [0, 0, 16], [0, 0, 16], [0, 0, 16], [0, 0, 16], [0, 0, 16], [1, 0, 15]]),
    expectedReplyStats: { edges: 99, min: 1, max: 7, average: 6.19 },
    hint: '先抬车 a1–a3，再横到 e3；白马走左翼三跳，不能被 d8 兵的横走节奏带偏。',
    motif: '66 防守边 · 侧兵扰动 · H9 首证',
    state: {
      turn: 'chess',
      ply: 0,
      pieces: [
        p('c-king', 'chess', 'king', 0, 0),
        p('c-rook', 'chess', 'rook', 0, 9),
        p('c-knight', 'chess', 'knight', 1, 0),
        p('x-general', 'xiangqi', 'general', 3, 7),
        p('x-block-left', 'xiangqi', 'soldier', 3, 9),
        p('x-block-right', 'xiangqi', 'soldier', 5, 9),
        p('x-screen', 'xiangqi', 'soldier', 3, 2),
      ],
    },
  },
];
