import type { GameState, Piece, Side } from './hybrid-engine';

export interface Puzzle {
  id: string;
  number: string;
  title: string;
  subtitle: string;
  material: '2 VS 4' | '3 VS 4' | '3 VS 5';
  human: Side;
  proofDepth: number;
  mateMoves: number;
  winnerTurns: number;
  uniqueWinnerTurns: number;
  expectedWinningMoveKeys: string[];
  expectedPrincipalVariationKeys: string[];
  hint: string;
  motif: string;
  state: GameState;
}

const p = (id: string, side: Side, type: Piece['type'], x: number, y: number): Piece => ({ id, side, type, x, y });

export const PUZZLES: Puzzle[] = [
  {
    id: 'three-branch-queen-net',
    number: '01',
    title: '三岔后网',
    subtitle: '你执象棋。首车横切后，黑方仍有三种合法防守；无论选择哪一支，第二次胜着都保持唯一。',
    material: '3 VS 5',
    human: 'xiangqi',
    proofDepth: 7,
    mateMoves: 2,
    winnerTurns: 2,
    uniqueWinnerTurns: 2,
    expectedWinningMoveKeys: ['28-08'],
    expectedPrincipalVariationKeys: ['28-08', '16-06', '08-06'],
    hint: '先把 c2 车横到 a2，等黑后进入 a4 后再沿 a 线收网。',
    motif: '三防全覆盖 · 横切 · 唯一双步',
    state: {
      turn: 'xiangqi',
      ply: 0,
      pieces: [
        p('x-general', 'xiangqi', 'general', 3, 9),
        p('x-chariot-low', 'xiangqi', 'chariot', 2, 8),
        p('x-chariot-high', 'xiangqi', 'chariot', 1, 3),
        p('c-king', 'chess', 'king', 0, 1),
        p('c-pawn-edge', 'chess', 'pawn', 7, 2),
        p('c-queen', 'chess', 'queen', 1, 6),
        p('c-pawn-top', 'chess', 'pawn', 2, 0),
        p('c-knight', 'chess', 'knight', 3, 3),
      ],
    },
  },
  {
    id: 'two-defense-rook-thread',
    number: '02',
    title: '双防穿针',
    subtitle: '你执国际象棋。少两子仍可强胜；红方有两种防守分支，但白车的两次落点在全部分支中都唯一。',
    material: '2 VS 4',
    human: 'chess',
    proofDepth: 7,
    mateMoves: 2,
    winnerTurns: 2,
    uniqueWinnerTurns: 2,
    expectedWinningMoveKeys: ['22-32'],
    expectedPrincipalVariationKeys: ['22-32', '55-34', '32-34'],
    hint: '白车先从 c8 到 d8；红马若垫到 d6，第二车必须立即吃入。',
    motif: '双防分支 · 穿针 · 以少胜多',
    state: {
      turn: 'chess',
      ply: 0,
      pieces: [
        p('x-general', 'xiangqi', 'general', 3, 7),
        p('x-chariot-low', 'xiangqi', 'chariot', 4, 8),
        p('x-horse', 'xiangqi', 'horse', 5, 5),
        p('x-chariot-high', 'xiangqi', 'chariot', 4, 7),
        p('c-king', 'chess', 'king', 0, 3),
        p('c-rook', 'chess', 'rook', 2, 2),
      ],
    },
  },
  {
    id: 'bishop-crossfire',
    number: '03',
    title: '双象交火',
    subtitle: '你执国际象棋。没有后与车，双象仍能利用九宫边界完成交叉封锁；两次胜着来自不同的象。',
    material: '3 VS 5',
    human: 'chess',
    proofDepth: 7,
    mateMoves: 2,
    winnerTurns: 2,
    uniqueWinnerTurns: 2,
    expectedWinningMoveKeys: ['55-66'],
    expectedPrincipalVariationKeys: ['55-66', '57-47', '76-58'],
    hint: '先让 f5 的象去 g4压缩九宫，再观察 h4 象通往 f2 的斜线。',
    motif: '双象协作 · 九宫边界 · 交叉封锁',
    state: {
      turn: 'chess',
      ply: 0,
      pieces: [
        p('x-general', 'xiangqi', 'general', 5, 7),
        p('x-elephant-right', 'xiangqi', 'elephant', 8, 7),
        p('x-elephant-left', 'xiangqi', 'elephant', 2, 7),
        p('x-advisor', 'xiangqi', 'advisor', 3, 7),
        p('x-chariot', 'xiangqi', 'chariot', 8, 9),
        p('c-king', 'chess', 'king', 0, 1),
        p('c-bishop-right', 'chess', 'bishop', 7, 6),
        p('c-bishop-center', 'chess', 'bishop', 5, 5),
      ],
    },
  },
  {
    id: 'corner-file-recapture',
    number: '04',
    title: '角线回收',
    subtitle: '你执象棋。黑方后象看似围住西洋王，红车却能把最远端的回防引到同一条边线再吃回。',
    material: '3 VS 5',
    human: 'xiangqi',
    proofDepth: 7,
    mateMoves: 2,
    winnerTurns: 2,
    uniqueWinnerTurns: 2,
    expectedWinningMoveKeys: ['79-89'],
    expectedPrincipalVariationKeys: ['79-89', '22-88', '89-88'],
    hint: 'h1 车先走 i1；黑后从 c8 赶到 i2 后，沿同一纵线完成回收。',
    motif: '远端引离 · 边线回收 · 双车',
    state: {
      turn: 'xiangqi',
      ply: 0,
      pieces: [
        p('x-general', 'xiangqi', 'general', 5, 8),
        p('x-chariot-low', 'xiangqi', 'chariot', 7, 9),
        p('x-chariot-high', 'xiangqi', 'chariot', 7, 0),
        p('c-king', 'chess', 'king', 8, 2),
        p('c-queen-left', 'chess', 'queen', 2, 2),
        p('c-queen-corner', 'chess', 'queen', 8, 0),
        p('c-bishop-edge', 'chess', 'bishop', 8, 1),
        p('c-bishop-top', 'chess', 'bishop', 6, 0),
      ],
    },
  },
  {
    id: 'seventh-rank-lure',
    number: '05',
    title: '七线诱车',
    subtitle: '你执国际象棋。白车横移一格制造唯一杀网；红车被迫侧挡后，第二步沿纵线完成终局。',
    material: '3 VS 4',
    human: 'chess',
    proofDepth: 7,
    mateMoves: 2,
    winnerTurns: 2,
    uniqueWinnerTurns: 2,
    expectedWinningMoveKeys: ['43-53'],
    expectedPrincipalVariationKeys: ['43-53', '45-55', '53-55'],
    hint: 'e7 车只横移到 f7；不要急着吃 e5 的红车。',
    motif: '诱离 · 横后直取 · 唯一节奏',
    state: {
      turn: 'chess',
      ply: 0,
      pieces: [
        p('x-general', 'xiangqi', 'general', 5, 9),
        p('x-chariot-high', 'xiangqi', 'chariot', 4, 5),
        p('x-chariot-low', 'xiangqi', 'chariot', 4, 9),
        p('x-cannon', 'xiangqi', 'cannon', 2, 9),
        p('c-king', 'chess', 'king', 8, 4),
        p('c-bishop', 'chess', 'bishop', 6, 9),
        p('c-rook', 'chess', 'rook', 4, 3),
      ],
    },
  },
  {
    id: 'advisor-deflection',
    number: '06',
    title: '仕线偏转',
    subtitle: '你执国际象棋。红仕是唯一能延缓终局的防守子；白车必须先占 d8，再在它落到 d3 时吃入。',
    material: '2 VS 4',
    human: 'chess',
    proofDepth: 7,
    mateMoves: 2,
    winnerTurns: 2,
    uniqueWinnerTurns: 2,
    expectedWinningMoveKeys: ['12-32'],
    expectedPrincipalVariationKeys: ['12-32', '48-37', '32-37'],
    hint: '从 b8 横到 d8，不要沿 b 线直接下压。',
    motif: '仕线偏转 · 单车强胜 · 两步唯一',
    state: {
      turn: 'chess',
      ply: 0,
      pieces: [
        p('x-general', 'xiangqi', 'general', 3, 9),
        p('x-soldier', 'xiangqi', 'soldier', 1, 7),
        p('x-chariot', 'xiangqi', 'chariot', 4, 9),
        p('x-advisor', 'xiangqi', 'advisor', 4, 8),
        p('c-king', 'chess', 'king', 0, 0),
        p('c-rook', 'chess', 'rook', 1, 2),
      ],
    },
  },
  {
    id: 'queen-on-eighth',
    number: '07',
    title: '后落八线',
    subtitle: '你执象棋。第一步不是将军，而是长车吃后；黑王唯一退到角落后，第二车沿整条八线完成杀局。',
    material: '3 VS 4',
    human: 'xiangqi',
    proofDepth: 7,
    mateMoves: 2,
    winnerTurns: 2,
    uniqueWinnerTurns: 2,
    expectedWinningMoveKeys: ['12-82'],
    expectedPrincipalVariationKeys: ['12-82', '01-00', '82-02'],
    hint: 'b8 车先横穿到 i8 吃后；黑王退角后再回到 a8。',
    motif: '先取后 · 长线回转 · 安静首着',
    state: {
      turn: 'xiangqi',
      ply: 0,
      pieces: [
        p('x-general', 'xiangqi', 'general', 4, 9),
        p('x-chariot', 'xiangqi', 'chariot', 1, 2),
        p('x-horse', 'xiangqi', 'horse', 1, 3),
        p('c-king', 'chess', 'king', 0, 1),
        p('c-rook', 'chess', 'rook', 1, 0),
        p('c-knight', 'chess', 'knight', 1, 1),
        p('c-queen', 'chess', 'queen', 8, 2),
      ],
    },
  },
  {
    id: 'elephant-interpose',
    number: '08',
    title: '相垫中宫',
    subtitle: '你执国际象棋。白车先占 e10，逼红相从 g5 垫到 e3；同一辆车随后纵贯七格完成终局。',
    material: '2 VS 4',
    human: 'chess',
    proofDepth: 7,
    mateMoves: 2,
    winnerTurns: 2,
    uniqueWinnerTurns: 2,
    expectedWinningMoveKeys: ['30-40'],
    expectedPrincipalVariationKeys: ['30-40', '65-47', '40-47'],
    hint: 'd10 车只需走到 e10；红相垫入后，沿 e 线直接吃到 e3。',
    motif: '相垫 · 纵贯 · 单车强胜',
    state: {
      turn: 'chess',
      ply: 0,
      pieces: [
        p('c-king', 'chess', 'king', 0, 0),
        p('c-rook', 'chess', 'rook', 3, 0),
        p('x-general', 'xiangqi', 'general', 4, 9),
        p('x-block-left', 'xiangqi', 'soldier', 3, 9),
        p('x-block-right', 'xiangqi', 'soldier', 5, 9),
        p('x-elephant', 'xiangqi', 'elephant', 6, 5),
      ],
    },
  },
];
