import type { GameState, Piece, Side } from './hybrid-engine';

export interface Puzzle {
  id: string;
  number: string;
  title: string;
  subtitle: string;
  material: '2 VS 4' | '3 VS 4' | '3 VS 5';
  human: Side;
  horizonMoves: number;
  expectedSafeMoveKeys: string[];
  hint: string;
  motif: string;
  state: GameState;
}

const p = (id: string, side: Side, type: Piece['type'], x: number, y: number): Piece => ({ id, side, type, x, y });

export const PUZZLES: Puzzle[] = [
  {
    id: 'cut-the-file',
    number: '01',
    title: '截断王道',
    subtitle: '你执象棋。黑车沿中路压住九宫，只剩一次主动交换能拆掉杀网。',
    material: '2 VS 4',
    human: 'xiangqi',
    horizonMoves: 4,
    expectedSafeMoveKeys: ['48-46'],
    hint: '不要只挡下一将；找一着能直接移除中路攻击子的棋。',
    motif: '牵制 · 主动交换 · 唯一着',
    state: {
      turn: 'xiangqi',
      ply: 0,
      pieces: [
        p('x-general', 'xiangqi', 'general', 4, 9),
        p('x-chariot', 'xiangqi', 'chariot', 4, 8),
        p('c-king', 'chess', 'king', 0, 0),
        p('c-rook', 'chess', 'rook', 4, 6),
        p('c-knight-left', 'chess', 'knight', 1, 8),
        p('c-knight-right', 'chess', 'knight', 7, 8),
      ],
    },
  },
  {
    id: 'northern-counterstroke',
    number: '02',
    title: '北境回击',
    subtitle: '你执国际象棋。三辆车锁死王翼，挡车若只退一步，下一手就是绝杀。',
    material: '2 VS 4',
    human: 'chess',
    horizonMoves: 4,
    expectedSafeMoveKeys: ['41-43'],
    hint: 'e 线上的城堡不能后退；它必须越过空点吃掉威胁源。',
    motif: '封锁 · 反击 · 唯一着',
    state: {
      turn: 'chess',
      ply: 0,
      pieces: [
        p('c-king', 'chess', 'king', 4, 0),
        p('c-rook', 'chess', 'rook', 4, 1),
        p('x-general', 'xiangqi', 'general', 4, 9),
        p('x-chariot-center', 'xiangqi', 'chariot', 4, 3),
        p('x-chariot-left', 'xiangqi', 'chariot', 3, 2),
        p('x-chariot-right', 'xiangqi', 'chariot', 5, 2),
      ],
    },
  },
  {
    id: 'the-soldier-watches',
    number: '03',
    title: '孤兵旁观',
    subtitle: '多出的一兵给了你更多合法着，却没有多给一条生路。识别“看似能走”的诱饵。',
    material: '3 VS 4',
    human: 'xiangqi',
    horizonMoves: 4,
    expectedSafeMoveKeys: ['48-46'],
    hint: '边兵不是答案；它的每一步都来不及解除九宫中的直接威胁。',
    motif: '诱饵 · 时间差 · 唯一着',
    state: {
      turn: 'xiangqi',
      ply: 0,
      pieces: [
        p('x-general', 'xiangqi', 'general', 4, 9),
        p('x-chariot', 'xiangqi', 'chariot', 4, 8),
        p('x-soldier', 'xiangqi', 'soldier', 0, 6),
        p('c-king', 'chess', 'king', 0, 0),
        p('c-rook', 'chess', 'rook', 4, 6),
        p('c-knight-left', 'chess', 'knight', 1, 8),
        p('c-knight-right', 'chess', 'knight', 7, 8),
      ],
    },
  },
  {
    id: 'diagonal-seal',
    number: '04',
    title: '斜线封门',
    subtitle: '你执国际象棋。这次不是唯一解：正面吃车，或让象从长斜线赶到中宫。',
    material: '3 VS 4',
    human: 'chess',
    horizonMoves: 4,
    expectedSafeMoveKeys: ['41-43', '00-44'],
    hint: '除了 e 线的车，观察 a10 到 e6 的整条斜线。',
    motif: '长斜线 · 双解 · 封堵',
    state: {
      turn: 'chess',
      ply: 0,
      pieces: [
        p('c-king', 'chess', 'king', 4, 0),
        p('c-rook', 'chess', 'rook', 4, 1),
        p('c-bishop', 'chess', 'bishop', 0, 0),
        p('x-general', 'xiangqi', 'general', 4, 9),
        p('x-chariot-center', 'xiangqi', 'chariot', 4, 3),
        p('x-chariot-left', 'xiangqi', 'chariot', 3, 2),
        p('x-chariot-right', 'xiangqi', 'chariot', 5, 2),
      ],
    },
  },
  {
    id: 'the-elephants-two-doors',
    number: '05',
    title: '相位双门',
    subtitle: '你执象棋。相不能过河，却恰好能在己方半场搭起第二道屏障。',
    material: '3 VS 5',
    human: 'xiangqi',
    horizonMoves: 4,
    expectedSafeMoveKeys: ['48-46', '29-47'],
    hint: '一条路是吃子，另一条路遵守“塞象眼”规则并落在 e3。',
    motif: '象眼 · 双解 · 防线重构',
    state: {
      turn: 'xiangqi',
      ply: 0,
      pieces: [
        p('x-general', 'xiangqi', 'general', 4, 9),
        p('x-chariot', 'xiangqi', 'chariot', 4, 8),
        p('x-elephant', 'xiangqi', 'elephant', 2, 9),
        p('c-king', 'chess', 'king', 0, 0),
        p('c-rook', 'chess', 'rook', 4, 6),
        p('c-knight-left', 'chess', 'knight', 1, 8),
        p('c-knight-right', 'chess', 'knight', 7, 8),
        p('c-pawn', 'chess', 'pawn', 8, 1),
      ],
    },
  },
  {
    id: 'the-quiet-knight',
    number: '06',
    title: '静默骑士',
    subtitle: '你执国际象棋。角落的马增加了选择，却无法参与 e 线争夺；胜负仍在中央。',
    material: '3 VS 5',
    human: 'chess',
    horizonMoves: 4,
    expectedSafeMoveKeys: ['41-43'],
    hint: '不要被角落里的马吸引。先处理两步之后必然落下的中路车。',
    motif: '过载 · 假选择 · 唯一着',
    state: {
      turn: 'chess',
      ply: 0,
      pieces: [
        p('c-king', 'chess', 'king', 4, 0),
        p('c-rook', 'chess', 'rook', 4, 1),
        p('c-knight', 'chess', 'knight', 0, 0),
        p('x-general', 'xiangqi', 'general', 4, 9),
        p('x-chariot-center', 'xiangqi', 'chariot', 4, 3),
        p('x-chariot-left', 'xiangqi', 'chariot', 3, 2),
        p('x-chariot-right', 'xiangqi', 'chariot', 5, 2),
        p('x-horse', 'xiangqi', 'horse', 0, 5),
      ],
    },
  },
  {
    id: 'western-palace-cutoff',
    number: '07',
    title: '西宫截车',
    subtitle: '九宫与杀网一起向左平移。边兵可以走，车也可以垫，但只有直接截掉纵线威胁才来得及。',
    material: '3 VS 4',
    human: 'xiangqi',
    horizonMoves: 4,
    expectedSafeMoveKeys: ['38-36'],
    hint: '黑车在 d4；不要缓冲，也不要走边兵，直接让红车从 d2 越到 d4。',
    motif: '移位杀网 · 速度 · 唯一着',
    state: {
      turn: 'xiangqi',
      ply: 0,
      pieces: [
        p('x-general', 'xiangqi', 'general', 3, 9),
        p('x-chariot', 'xiangqi', 'chariot', 3, 8),
        p('x-soldier', 'xiangqi', 'soldier', 7, 6),
        p('c-king', 'chess', 'king', 8, 0),
        p('c-rook', 'chess', 'rook', 3, 6),
        p('c-knight-left', 'chess', 'knight', 0, 8),
        p('c-knight-right', 'chess', 'knight', 6, 8),
      ],
    },
  },
  {
    id: 'same-capture-different-fate',
    number: '08',
    title: '同吃异命',
    subtitle: '车与马都能吃到 f4 的黑车，但“吃掉威胁”并不等于“解除杀网”。两种交换只有一种能活。',
    material: '3 VS 5',
    human: 'xiangqi',
    horizonMoves: 4,
    expectedSafeMoveKeys: ['58-56'],
    hint: '比较红车 f2×f4 与红马 d5×f4 之后，哪一枚棋还能封住王将附近的直线。',
    motif: '同格异效 · 假解 · 唯一着',
    state: {
      turn: 'xiangqi',
      ply: 0,
      pieces: [
        p('x-general', 'xiangqi', 'general', 5, 9),
        p('x-chariot', 'xiangqi', 'chariot', 5, 8),
        p('x-horse', 'xiangqi', 'horse', 3, 5),
        p('c-king', 'chess', 'king', 0, 0),
        p('c-rook', 'chess', 'rook', 5, 6),
        p('c-knight-left', 'chess', 'knight', 2, 8),
        p('c-knight-right', 'chess', 'knight', 8, 8),
        p('c-bishop', 'chess', 'bishop', 6, 3),
      ],
    },
  },
  {
    id: 'left-wing-two-doors',
    number: '09',
    title: '左翼双门',
    subtitle: '王域整体偏向 d 线。这次有两条生路：正面拆车，或让长斜线上的象先吃掉侧翼封锁子。',
    material: '3 VS 4',
    human: 'chess',
    horizonMoves: 4,
    expectedSafeMoveKeys: ['31-33', '00-22'],
    hint: '除了 Rd9×d7，还要检查白象从 a10 到 c8 的短斜线。',
    motif: '偏翼构型 · 斜取 · 双解',
    state: {
      turn: 'chess',
      ply: 0,
      pieces: [
        p('c-king', 'chess', 'king', 3, 0),
        p('c-rook', 'chess', 'rook', 3, 1),
        p('c-bishop', 'chess', 'bishop', 0, 0),
        p('x-general', 'xiangqi', 'general', 3, 9),
        p('x-chariot-center', 'xiangqi', 'chariot', 3, 3),
        p('x-chariot-left', 'xiangqi', 'chariot', 2, 2),
        p('x-chariot-right', 'xiangqi', 'chariot', 4, 2),
      ],
    },
  },
  {
    id: 'eastern-knight-decoy',
    number: '10',
    title: '东翼马饵',
    subtitle: '角马确实能吃掉一辆侧车，却仍会在三回合内落败；中央车的主动交换才是唯一生路。',
    material: '3 VS 5',
    human: 'chess',
    horizonMoves: 4,
    expectedSafeMoveKeys: ['51-53'],
    hint: '先比较 Rf9×f7 与 Nh10×g8。少吃一辆侧车，反而能保住王。',
    motif: '贪吃诱饵 · 中央交换 · 唯一着',
    state: {
      turn: 'chess',
      ply: 0,
      pieces: [
        p('c-king', 'chess', 'king', 5, 0),
        p('c-rook', 'chess', 'rook', 5, 1),
        p('c-knight', 'chess', 'knight', 7, 0),
        p('x-general', 'xiangqi', 'general', 5, 9),
        p('x-chariot-center', 'xiangqi', 'chariot', 5, 3),
        p('x-chariot-left', 'xiangqi', 'chariot', 4, 2),
        p('x-chariot-right', 'xiangqi', 'chariot', 6, 2),
        p('x-soldier', 'xiangqi', 'soldier', 0, 6),
      ],
    },
  },
  {
    id: 'tenth-rank-countercheck',
    number: '11',
    title: '十阶反将',
    subtitle: '黑后与双马已经织成杀网，红车却不必追后。唯一生路是越过整条 d 线，在最北端夺回先手。',
    material: '3 VS 4',
    human: 'xiangqi',
    horizonMoves: 4,
    expectedSafeMoveKeys: ['38-30'],
    hint: '从 d2 一直看到 d10：那一格没有棋子，却能让红车立刻形成反将。',
    motif: '远程反将 · 夺先 · 唯一着',
    state: {
      turn: 'xiangqi',
      ply: 0,
      pieces: [
        p('x-general', 'xiangqi', 'general', 3, 9),
        p('x-chariot', 'xiangqi', 'chariot', 3, 8),
        p('x-soldier', 'xiangqi', 'soldier', 7, 6),
        p('c-king', 'chess', 'king', 8, 0),
        p('c-queen', 'chess', 'queen', 7, 7),
        p('c-knight-left', 'chess', 'knight', 0, 8),
        p('c-knight-right', 'chess', 'knight', 6, 8),
      ],
    },
  },
  {
    id: 'second-rank-crosscut',
    number: '12',
    title: '横断二线',
    subtitle: '威胁不再从纵线逼近，而是潜到红车身旁。八个合法选择中，只有一次横向交换能拆网。',
    material: '3 VS 4',
    human: 'xiangqi',
    horizonMoves: 4,
    expectedSafeMoveKeys: ['38-48'],
    hint: '红车与黑车都在第二横线；先检查一步即可完成的 d2×e2。',
    motif: '横向交换 · 近身威胁 · 唯一着',
    state: {
      turn: 'xiangqi',
      ply: 0,
      pieces: [
        p('x-general', 'xiangqi', 'general', 3, 9),
        p('x-chariot', 'xiangqi', 'chariot', 3, 8),
        p('x-soldier', 'xiangqi', 'soldier', 7, 6),
        p('c-king', 'chess', 'king', 8, 0),
        p('c-rook', 'chess', 'rook', 4, 8),
        p('c-knight-center', 'chess', 'knight', 3, 5),
        p('c-knight-right', 'chess', 'knight', 6, 8),
      ],
    },
  },
  {
    id: 'quiet-horse-second-door',
    number: '13',
    title: '静马第二门',
    subtitle: '正面吃车当然能活，但演化搜索还找到一着不吃子的退马。它看似离开战场，却恰好重写后续杀网。',
    material: '3 VS 5',
    human: 'xiangqi',
    horizonMoves: 4,
    expectedSafeMoveKeys: ['58-56', '24-12'],
    hint: '第一解是车 f2×f4；第二解藏在红马 c6 到 b8 的安静一步。',
    motif: '静着 · 马步重构 · 双解',
    state: {
      turn: 'xiangqi',
      ply: 0,
      pieces: [
        p('x-general', 'xiangqi', 'general', 5, 9),
        p('x-chariot', 'xiangqi', 'chariot', 5, 8),
        p('x-horse', 'xiangqi', 'horse', 2, 4),
        p('c-king', 'chess', 'king', 0, 0),
        p('c-rook', 'chess', 'rook', 5, 6),
        p('c-knight-left', 'chess', 'knight', 2, 8),
        p('c-knight-right', 'chess', 'knight', 8, 8),
        p('c-bishop', 'chess', 'bishop', 6, 3),
      ],
    },
  },
  {
    id: 'two-captures-one-axis',
    number: '14',
    title: '双子夺轴',
    subtitle: '中路象棋车是杀网轴心。西洋车可以正面交换，骑士也能从 c8 跃入同一格，形成真正的双解。',
    material: '3 VS 5',
    human: 'chess',
    horizonMoves: 4,
    expectedSafeMoveKeys: ['41-43', '22-43'],
    hint: 'e7 是共同目标：比较 Re9×e7 与 Nc8×e7。',
    motif: '共同目标 · 双子捕获 · 双解',
    state: {
      turn: 'chess',
      ply: 0,
      pieces: [
        p('c-king', 'chess', 'king', 4, 0),
        p('c-rook', 'chess', 'rook', 4, 1),
        p('c-knight', 'chess', 'knight', 2, 2),
        p('x-general', 'xiangqi', 'general', 4, 9),
        p('x-chariot-center', 'xiangqi', 'chariot', 4, 3),
        p('x-chariot-left', 'xiangqi', 'chariot', 3, 2),
        p('x-chariot-right', 'xiangqi', 'chariot', 5, 2),
        p('x-horse', 'xiangqi', 'horse', 0, 5),
      ],
    },
  },
  {
    id: 'bishop-labyrinth',
    number: '15',
    title: '象路迷城',
    subtitle: '角落长象带来十个合法选择，其中一些要到第四次反击才显出败因；真正生路仍只有中央交换。',
    material: '3 VS 5',
    human: 'chess',
    horizonMoves: 4,
    expectedSafeMoveKeys: ['41-43'],
    hint: '不要用“象能走得很远”代替计算。先确认 e7 的轴心是否仍然存在。',
    motif: '长斜线诱惑 · 深层反驳 · 唯一着',
    state: {
      turn: 'chess',
      ply: 0,
      pieces: [
        p('c-king', 'chess', 'king', 4, 0),
        p('c-rook', 'chess', 'rook', 4, 1),
        p('c-bishop', 'chess', 'bishop', 8, 0),
        p('x-general', 'xiangqi', 'general', 4, 9),
        p('x-chariot-center', 'xiangqi', 'chariot', 4, 3),
        p('x-chariot-left', 'xiangqi', 'chariot', 3, 2),
        p('x-chariot-right', 'xiangqi', 'chariot', 5, 2),
        p('x-horse', 'xiangqi', 'horse', 0, 5),
      ],
    },
  },
  {
    id: 'three-square-pursuit',
    number: '16',
    title: '三格追车',
    subtitle: '中路威胁退到 f6，安全交换因此变成长距离追击。骑士的近手全是诱饵，车必须一次走完三格。',
    material: '3 VS 5',
    human: 'chess',
    horizonMoves: 4,
    expectedSafeMoveKeys: ['51-54'],
    hint: 'f8 与 f7 都是空点；白车可以从 f9 直接越到 f6 吃车。',
    motif: '长距离捕获 · 空点穿越 · 唯一着',
    state: {
      turn: 'chess',
      ply: 0,
      pieces: [
        p('c-king', 'chess', 'king', 5, 0),
        p('c-rook', 'chess', 'rook', 5, 1),
        p('c-knight', 'chess', 'knight', 7, 0),
        p('x-general', 'xiangqi', 'general', 5, 9),
        p('x-chariot-center', 'xiangqi', 'chariot', 5, 4),
        p('x-chariot-left', 'xiangqi', 'chariot', 4, 2),
        p('x-chariot-right', 'xiangqi', 'chariot', 6, 2),
        p('x-soldier', 'xiangqi', 'soldier', 0, 6),
      ],
    },
  },
];
